#! /bin/bash

latex scopatz_defense_pres_short.tex
bibtex scopatz_defense_pres_short.aux
latex scopatz_defense_pres_short.tex
latex scopatz_defense_pres_short.tex
dvipdf scopatz_defense_pres_short.dvi
